const GH='https://maryza2603.github.io/moy-proekt/';
const W=[
 {cat:'konstr',t:'Дробильная установка «ГорТехПоставка»',f:'Для производства',img:'drobilki-konfig',d:'B2B-конфигуратор: тип дробилки, производительность, шасси, привод и опции. Чертёж, цена, масса и срок поставки меняются сразу, смета в PDF и ссылка для коллег.',url:GH+'drobilki-konfig/',b:['B2B']},
 {cat:'konstr',t:'Бассейн «Лагуна»',f:'Для строителей',img:'bassein',d:'Лендинг компании с конструктором: форма и размер чаши, отделка, подсветка - смета считается сразу.',url:GH+'bassein/'},
 {cat:'konstr',t:'Кухня «Олива»',f:'Для производства',img:'kuhnya',d:'Кухня под размер стены: модули, фасады и столешница меняются на картинке, цена пересчитывается.',url:GH+'kuhnya/'},
 {cat:'konstr',t:'Кольцо «Аурум»',f:'Для ювелиров',img:'koltso',d:'Ювелирная мастерская: металл, камень и огранка - кольцо собирается на глазах вместе с ценой.',url:GH+'koltso/'},
 {cat:'konstr',t:'Баня под ключ',f:'Для строителей',img:'banya',d:'Планировка бани из комнат, печь, фундамент и кровля - смета в PDF и заявка в один клик.',url:GH+'banya/'},
 {cat:'konstr',t:'Планировщик сада',f:'Для ландшафта',img:'sad',d:'Участок любой формы, зоны и растения - площади и смета считаются автоматически.',url:GH+'sad/'},
 {cat:'konstr',t:'Входная дверь',f:'Для производства',img:'door',d:'Картинка двери собирается из слоёв: цвет, ручка, стекло - цена считается сразу.',url:'https://maryza2603.github.io/moy-proekt/portfolio/demo/door/'},
 {cat:'code',land:1,t:'Текстиль «Лён и Мёд»',f:'Для маркетплейсов',img:'len-i-med',d:'Лендинг бренда для продавца на WB и Ozon: каталог с выбором размера и цены, кнопки «Купить на Wildberries» и «Купить на Ozon», материалы, отзывы, уход. Карточки товаров - тоже мои.',url:GH+'len-i-med/',b:['Лендинг','Маркетплейсы']},
{cat:'code',t:'Стоматология «Фарфор»',f:'Для клиник',img:'stomat',d:'Сайт клиники с онлайн-записью: пациент выбирает врача, день и свободное время. Прайс с поиском, врачи, отзывы, карта.',url:GH+'demo-stomatologiya/',b:['Премиум','Онлайн-запись']},
 {cat:'code',t:'Загородный комплекс «Тихая Сосна»',f:'Для баз отдыха',img:'baza',d:'Сайт базы отдыха с бронированием: календарь занятости домиков, расчёт стоимости с баней и завтраками, предоплата.',url:GH+'demo-baza-otdyha/',b:['Премиум','Бронирование']},
 {cat:'code',t:'Ресторан «Угли»',f:'Для ресторанов',img:'restoran',d:'Сайт ресторана с бронированием стола: схема зала, выбор даты, времени и гостей, меню с фото, заявка на банкет.',url:GH+'demo-restoran/',b:['Премиум','Бронь стола']},
 {cat:'code',t:'Детейлинг-центр «Глосс»',f:'Для автосервисов',img:'detailing',d:'Сайт детейлинга: калькулятор цены по классу авто, слайдер «до/после», запись на бокс и время.',url:GH+'demo-detailing/',b:['Премиум','Калькулятор']},
 {cat:'code',t:'Юристы «Корсаков и партнёры»',f:'Для юридических компаний',img:'yurist',d:'Сайт юридической фирмы: тест из 4 вопросов с оценкой стоимости, срока и плана работы, команда юристов.',url:GH+'demo-yurist/',b:['Премиум','Квиз']},
 {cat:'code',t:'Йога-студия «Дыши»',f:'Для фитнеса и йоги',img:'yoga',d:'Сайт студии: расписание недели с фильтрами и свободными местами, запись на занятие, подбор абонемента.',url:GH+'demo-yoga/',b:['Премиум','Расписание']},
 {cat:'code',t:'Психологи: женская и мужская версия',f:'Для психологов',d:'Два сайта психологов в едином стиле - одна система дизайна под разных специалистов.',pair:['psy-w','psy-m'],labels:['Анна','Михаил'],links:[['Сайт 1',GH+'psy-konsultaciya/'],['Сайт 2',GH+'psy-mikhail/']],wide:1,b:['Серия']},
 {cat:'code',t:'Риэлтор Ирина Ветрова',f:'Для риэлторов',img:'rieltor',d:'Сайт-визитка риэлтора: объекты с фильтром, услуги с ценами, шаги сделки и калькулятор - покупатель узнаёт цену квартиры мечты, продавец - за сколько продать свою.',url:GH+'rieltor/'},
 {cat:'code',t:'Студия маникюра «Миндаль»',f:'Для салонов красоты',img:'mindal',d:'Сайт для мастера маникюра и педикюра: работы с просмотром фото, услуги с ценами, палитра и онлайн-запись: клиент сам выбирает услугу, мастера и свободное время. На рабочем сайте запись приходит мастеру в Telegram, а занятое время сразу пропадает из расписания.',url:GH+'mindal/',b:['Онлайн-запись']},
 {cat:'code',t:'Наталья Пхенда, консультант по питанию',f:'Для экспертов',img:'natalya',d:'Сайт для реального клиента: КМС по плаванию и экономист, питание без жёстких запретов. Услуги и цены, первые результаты клиентов, запись в MAX, почту и ВК.',url:GH+'natalya-pitanie/',b:['Реальный клиент','Стиль по визиткам']},
 {cat:'code',t:'Преподаватель английского',f:'Для репетиторов',img:'english',d:'Сайт репетитора: направления, как проходит урок, отзывы, цены и запись на пробный урок с выбором дня и времени.',url:GH+'english-tutor-v2/'},
 {cat:'code',land:1,t:'Контент-Лаборатория',f:'Для команд и агентств',img:'weapons',d:'Яркий лендинг для команды, которая создаёт контент.',url:GH+'weapons/'},
 {cat:'code',t:'Дробильное оборудование «ГорТехПоставка»',f:'Для производства',img:'drobilki',d:'Сайт поставщика дробилок для карьеров: квиз-подбор модели за 3 вопроса, запрос КП и опросного листа.',url:GH+'drobilki/',b:['B2B','Квиз-подбор']},
 {cat:'code',t:'Строительная компания',f:'Для строителей',img:'stroyka',d:'Сайт подрядчика: услуги, объекты, расчёт стоимости.',url:GH+'stroyka/'},
 {cat:'code',t:'Двери и шкафы-купе',f:'Для производства',img:'dveri',d:'Каталог и заявка на замер для производителя мебели.',url:GH+'dveri-kupe/'},
 {cat:'code',t:'Студия дизайна интерьера',f:'Для дизайнеров',img:'interior',d:'Стильный сайт с портфолио интерьеров.',url:GH+'interior/'},
 {cat:'code',t:'Преподаватель математики',f:'Для репетиторов',img:'math',d:'Сайт репетитора для школьников и подготовки к экзаменам.',url:GH+'math-tutor/'},
 {cat:'code',t:'ПК-мастер',f:'Для мастеров услуг',img:'pc',d:'Сайт частного мастера по ремонту компьютеров.',url:GH+'pc-master/'},
 {cat:'code',t:'Загородные дома',f:'Для строителей',img:'zagorod',d:'Строительство загородных домов: проекты, цены, этапы.',url:GH+'zagorodnye-doma/'},
 {cat:'tilda',land:1,t:'«Заговори на английском за 2 месяца»',f:'Для онлайн-школ',img:'t-eng',d:'Продающий лендинг онлайн-курса английского.',url:'https://zagovorieng.tilda.ws/'},
 {cat:'tilda',land:1,t:'«Стоп, тревога!» - мини-курс',f:'Для психологов',img:'t-kurpatov',d:'Лендинг мини-курса Андрея Курпатова.',url:'https://psiholog8.tilda.ws/'},
 {cat:'tilda',land:1,t:'Школа рисования «Акварель»',f:'Для онлайн-школ',img:'t-akvarel',d:'Нежный лендинг художественной школы.',url:'https://tsvetishcool.tilda.ws/'},
 {cat:'tilda',t:'Детская стоматология',f:'Для клиник',img:'t-zubki',d:'Дружелюбный сайт детской клиники.',url:'https://detkizubki.tilda.ws/'},
 {cat:'tilda',t:'Еда Азии',f:'Для кафе и доставки',img:'t-asia',d:'Сайт ресторана азиатской кухни.',url:'https://project10946381.tilda.ws/'},
 {cat:'tilda',land:1,t:'«Научись спать правильно»',f:'Для экспертов',img:'t-son',d:'Лендинг онлайн-курса о здоровом сне.',url:'https://project10651681.tilda.ws/myproject1'},
 {cat:'tilda',land:1,t:'Мастер-класс «Бургер»',f:'Для кафе и доставки',img:'t-burger',d:'Лендинг кулинарного мастер-класса.',url:'https://project10705053.tilda.ws/'},
 {cat:'app',t:'Telegram-бот для заявок с сайта',f:'Для любого бизнеса',gif:'demo-bot-mindal.gif',d:'Клиент записывается на сайте - мастер через секунду получает запись в Telegram: имя, телефон, услуга, дата и цена. Подключается к любому сайту, в том числе к Тильде. Попробуйте сами: подключите демо-бота и запишитесь.',links:[['Попробовать на сайте',GH+'mindal/#book'],['Бот в Telegram','https://t.me/mindal_demo_bot']],b:['Telegram-бот']},
 {cat:'app',t:'Калькулятор строительства дома',f:'Для строителей',img:'anapa',d:'Сайт строительства домов у моря с расчётом стоимости дома по площади, этажам и материалам.',url:GH+'anapa-dom/',b:['Калькулятор']},
 {cat:'app',t:'Калькулятор металлоконструкций',f:'Для производства',img:'metall',d:'Сайт производителя металлоконструкций с расчётом стоимости изделия.',url:GH+'metall/',b:['Калькулятор']},
 {cat:'app',t:'Калькулятор лестниц',f:'Для производства',img:'lestnicy',d:'Сайт производителя лестниц с расчётом стоимости по форме, материалу и ограждению.',url:GH+'lestnicy/',b:['Калькулятор']},
 {cat:'app',t:'Ремонт коммерческих помещений',f:'Для строителей',img:'remont',d:'Расчёт ремонта офиса, магазина или кафе за минуту - по площади и виду работ.',url:GH+'remont/',b:['Калькулятор']},
 {cat:'app',t:'Калькулятор КБЖУ',f:'Для экспертов',img:'nutri',d:'Сайт нутрициолога: норма калорий и КБЖУ по параметрам клиента и запись на консультацию.',url:GH+'nutri/',b:['Калькулятор']},
 {cat:'app',t:'Клининговая компания',f:'Для сервисов услуг',img:'cleaning',d:'«Чистый дом» - демо двух приложений: для клиента (заказ уборки с расчётом цены) и для клинера (заявки и выплаты).',url:GH+'cleaning/',b:['Веб-приложение']},
 {cat:'app',t:'Арена - приложение для Android',mock:'phone',d:'Личное Android-приложение для сервиса «Арена»: всё под рукой в телефоне, без браузера.',b:['Android']},
 {cat:'app',t:'Биржа фриланса - приложение',mock:'phone',d:'У биржи не было приложения - я сделала своё. Заказы и отклики прямо с телефона.',b:['Android']},
 {cat:'app',t:'Видеостудия для Windows',mock:'pc',d:'Программа на Python: озвучка видео русским голосом по субтитрам, транскрибация, скачивание видео, Reels.',b:['Windows','Python']},
];
const EXP=['Для психологов','Для экспертов','Для репетиторов','Для онлайн-школ'];
const CATS=[['all','Все'],['konstr','Конструкторы'],['code','Сайты на коде'],['land','Лендинги'],['expert','Для экспертов'],['tilda','Tilda'],['app','Приложения'],['design','Дизайн']];
const BADGE={konstr:['konstr','Конструктор'],code:['code','Код'],tilda:['tilda','Tilda'],app:['app','Приложение']};

/* дизайн: картинки лежат в img/design/<папка>/, презентации - в docs/ */
const DESIGN=[
 {g:'Логотипы',p:'Фирменные знаки для бизнеса разных сфер',cls:'logos',h:240,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo2/01.webp", "Сладкий день - домашние торты"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/04.webp", "Семейная винодельня"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/01.webp", "Apex - логистика"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/03.webp", "Свежий сок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/02.webp", "FreshJuice"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/05.webp", "AquaFresh"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo2/02.webp", "Мотор - автосервис"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/06.webp", "Cerme Rad - строительство"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/logo/08.webp", "World of Discoveries - туризм"]]},
 {g:'Карточки для маркетплейсов',p:'Стиль подбираю под товар и покупателя. «Лён и Мёд» - спокойная серия текстильного бренда в одной гамме. Массажёр и термокружка - контрастная техника с крупным заголовком. Отпариватель - яркий бирюзовый с цифрами и плашками. Косметичка - lifestyle-фото с моделью для женской аудитории',h:380,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/t1.webp", "«Лён и Мёд»: плед"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/t2.webp", "«Лён и Мёд»: постельное бельё"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/t3.webp", "«Лён и Мёд»: полотенца"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/01.webp", "Массажёр - контрастный стиль"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/02.webp", "Массажёр"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/03.webp", "Массажёр"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/04.webp", "Массажёр"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/05.webp", "Массажёр"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/06.webp", "Массажёр"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/07.webp", "Термокружка - контрастный стиль"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/08.webp", "Термокружка"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/09.webp", "Термокружка"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/10.webp", "Термокружка"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/12.webp", "Косметичка - lifestyle с моделью"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/13.webp", "Отпариватель - яркий бирюзовый"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/14.webp", "Отпариватель"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/15.webp", "Отпариватель"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/mp/16.webp", "Отпариватель"]]},
 {g:'Оформление соцсетей',p:'Обложки, аватарки, посты и сторис для ВК, YouTube и Телеграм',h:300,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/08.webp", "Ремонт без нервов - ВК"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/09.webp", "Ремонт без нервов"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/10.webp", "Ремонт без нервов"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/11.webp", "Ремонт без нервов - YouTube"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/12.webp", "Цветочная мастерская"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/13.webp", "Цветочная мастерская"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/14.webp", "Цветочная мастерская"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/01.webp", "Дачные секреты - ВК"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/02.webp", "Дачные секреты"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/03.webp", "Дачные секреты"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/04.webp", "Отношения - пост"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/05.webp", "Отношения - сторис"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/06.webp", "Отношения"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/smm/07.webp", "Отношения - обложка видео"]]},
 {g:'Стикеры для Телеграм',p:'Наборы персонажей: ёжик, зайчик и лисёнок',cls:'stk',h:200,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/01.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/02.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/03.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/04.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/05.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/06.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/07.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/08.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/09.webp", "Ёжик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/10.webp", "Зайчик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/11.webp", "Зайчик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/12.webp", "Зайчик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/13.webp", "Зайчик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/14.webp", "Зайчик"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/15.webp", "Лисёнок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/16.webp", "Лисёнок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/17.webp", "Лисёнок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/18.webp", "Лисёнок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/19.webp", "Лисёнок"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/stickers/20.webp", "Лисёнок"]]},
 {g:'Карусель для соцсетей',p:'Пост-карусель «Как вести бизнес в 2026 году»',h:380,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/01.webp", "Слайд 1"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/02.webp", "Слайд 2"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/03.webp", "Слайд 3"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/04.webp", "Слайд 4"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/05.webp", "Слайд 5"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/carousel/06.webp", "Слайд 6"]]},
 {g:'Ретушь фото',p:'Слева - до, справа - после',h:280,items:[["https://maryza2603.github.io/moy-proekt/portfolio/img/design/retouch/01.webp", "Кафе"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/retouch/02.webp", "Кружка"], ["https://maryza2603.github.io/moy-proekt/portfolio/img/design/retouch/03.webp", "Ваза"]]},
 {g:'Презентации',p:'Нажмите на обложку, чтобы открыть PDF',pres:[["https://maryza2603.github.io/moy-proekt/portfolio/docs/kofepro.pdf", "КофеПро Сервис", "B2B", "https://maryza2603.github.io/moy-proekt/portfolio/img/design/pres/kofepro.webp"], ["https://maryza2603.github.io/moy-proekt/portfolio/docs/utro-v-polyah.pdf", "Утро в полях", "для ритейл-сети", "https://maryza2603.github.io/moy-proekt/portfolio/img/design/pres/utro-v-polyah.webp"], ["https://maryza2603.github.io/moy-proekt/portfolio/docs/teplyi-dvor.pdf", "Пекарня «Тёплый двор»", "для бизнеса", "https://maryza2603.github.io/moy-proekt/portfolio/img/design/pres/teplyi-dvor.webp"], ["https://maryza2603.github.io/moy-proekt/portfolio/docs/delovaya-perepiska.pdf", "7 принципов деловой переписки", "обучение", "https://maryza2603.github.io/moy-proekt/portfolio/img/design/pres/delovaya-perepiska.webp"], ["https://maryza2603.github.io/moy-proekt/portfolio/docs/foto-na-telefon.pdf", "Снимай на телефон как профи", "мини-курс", "https://maryza2603.github.io/moy-proekt/portfolio/img/design/pres/foto-na-telefon.webp"]]},
];

const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const designCount=DESIGN.reduce((n,g)=>n+(g.items||g.pres).length,0);
function shot(w){
  if(w.pair) return `<div class="shot pair"><div class="chrome"><i></i><i></i><i></i></div>${w.pair.map((p,i)=>`<div class="half"><img decoding="async" src="https://maryza2603.github.io/moy-proekt/portfolio/img/sites/${p}.webp" alt="${w.t} - ${w.labels[i]}"><span class="label">${w.labels[i]}</span></div>`).join('')}</div>`;
  if(w.gif) return `<div class="shot"><img class="gif" decoding="async" src="https://maryza2603.github.io/moy-proekt/portfolio/video/${w.gif}" alt="${esc(w.t)}"></div>`;
  if(w.mock==='phone') return `<div class="shot"><div class="appmock"><div class="device"><div class="top"></div><div class="it"></div><div class="it"></div><div class="it" style="width:70%"></div><div class="it"></div></div></div></div>`;
  if(w.mock==='pc') return `<div class="shot"><div class="appmock"><div class="pc"><div class="tb"><i></i><i></i><i></i></div><div class="tabs"><span>Озвучка</span><span>Транскрибация</span><span>Скачивание</span><span>Reels</span></div><div class="pane"><div class="ln"></div><div class="ln" style="width:70%"></div><div class="ln" style="width:85%"></div><div class="go"></div></div></div></div></div>`;
  return `<div class="shot"><div class="chrome"><i></i><i></i><i></i></div><img class="scroll" decoding="async" src="https://maryza2603.github.io/moy-proekt/portfolio/img/sites/${w.img}.webp" alt="${esc(w.t)}"></div>`;
}
function card(w,i){
  const bd=[...(w.f?[['for',w.f]]:[]),BADGE[w.cat],...(w.b||[]).map(x=>[x==='Премиум'?'prem':'',x])].map(([c,x])=>`<span class="badge ${c}">${x}</span>`).join('');
  const links=w.links?w.links:(w.url?[['Открыть',w.url]]:[]);
  const foot=links.length?`<div class="links">${links.map(([l,u])=>`<a href="${u}" target="_blank" rel="noopener">${l}<svg><use href="#ext"/></svg></a>`).join('')}</div>`:`<div class="no-link"><svg width="15" height="15"><use href="#lock"/></svg>Личное приложение - покажу на созвоне</div>`;
  return `<article class="card${w.wide?' wide':''}" style="animation-delay:${Math.min(i,8)*50}ms">${shot(w)}<div class="body"><div class="badges">${bd}</div><h3>${esc(w.t)}</h3><p>${esc(w.d)}</p>${foot}</div></article>`;
}
const ARR='<svg viewBox="0 0 24 24"><use href="#arrow"/></svg>';
function renderDesign(){
  return DESIGN.map((g,gi)=>{
    const strip=!!g.items;
    const inner=strip
      ?`<div class="strip ${g.cls||''}" style="--h:${g.h}px">${g.items.map(([src,cap],i)=>`<figure data-g="${gi}" data-i="${i}"><img decoding="async" src="${src}" alt="${esc(cap)}">${g.cls?'':`<figcaption>${esc(cap)}</figcaption>`}</figure>`).join('')}</div>`
      :`<div class="pres">${g.pres.map(([u,t,s,img])=>`<a href="${u}" target="_blank" rel="noopener"><img decoding="async" src="${img}" alt="${esc(t)}"><span><b>${esc(t)}</b><small>PDF · ${esc(s)}</small></span></a>`).join('')}</div>`;
    const nav=strip?`<div class="dz-nav"><button data-dir="-1" aria-label="Назад" style="transform:scaleX(-1)">${ARR}</button><button data-dir="1" aria-label="Вперёд">${ARR}</button></div>`:'';
    return `<div class="dz-group" id="dz-${gi}"><div class="dz-head"><div><h3><svg class="star"><use href="#star"/></svg>${g.g}</h3><p>${g.p}</p></div>${nav}</div>${inner}</div>`;
  }).join('');
}
function show(cat){
  document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('on',b.dataset.c===cat));
  const list=W.filter(w=>cat==='all'||w.cat===cat||(cat==='land'&&w.land)||(cat==='expert'&&EXP.includes(w.f)));
  $('#grid').style.display=list.length?'':'none';
  $('#grid').innerHTML=list.map(card).join('');
  const d=$('#design'); d.style.display=(cat==='design'||cat==='all')?'':'none';
  d.style.marginTop=cat==='all'?'70px':'0';
  d.innerHTML=(cat==='all'&&designCount?`<h2 style="font-size:36px;margin-bottom:30px">Дизайн</h2>`:'')+(cat==='all'&&!designCount?'':renderDesign());
}
$('#filters').innerHTML=CATS.map(([c,l])=>{const n=c==='all'?W.length+designCount:c==='design'?designCount:c==='land'?W.filter(w=>w.land).length:c==='expert'?W.filter(w=>EXP.includes(w.f)).length:W.filter(w=>w.cat===c).length;return (c==='design'&&!n)?'':`<button data-c="${c}">${l}<sup>${n}</sup></button>`}).join('');
$('#filters').onclick=e=>{const b=e.target.closest('button');if(b)show(b.dataset.c)};
show('all');
$('#cnt-sites').textContent=W.filter(w=>w.cat!=='app').reduce((n,w)=>n+(w.pair&&w.labels[0]!=='Было'?2:1),0)+'';

document.addEventListener('click',e=>{const a=e.target.closest('[data-dz]');if(!a)return;e.preventDefault();show('design');const g=DESIGN.findIndex(x=>x.g.startsWith('Карточки'));const el=document.getElementById('dz-'+g);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})});
// карточки услуг: клик - фильтр и прокрутка к примерам
function goSvc(el){const g=el.dataset.go;
  if(g.startsWith('dz:')){show('design');const i=DESIGN.findIndex(x=>x.g.startsWith(g.slice(3)));const d=document.getElementById('dz-'+i);if(d)d.scrollIntoView({behavior:'smooth'})}
  else{show(g);$('#filters').scrollIntoView({behavior:'smooth'})}}
document.addEventListener('click',e=>{const s=e.target.closest('.svc[data-go]');if(!s||e.target.closest('a,video,button'))return;goSvc(s)});
document.addEventListener('keydown',e=>{const s=e.target.closest&&e.target.closest('.svc[data-go]');if(s&&(e.key==='Enter'||e.key===' ')&&e.target===s){e.preventDefault();goSvc(s)}});
// ленты и лайтбокс
document.addEventListener('click',e=>{
  const nb=e.target.closest('.dz-nav button');
  if(nb){const st=nb.closest('.dz-group').querySelector('.strip');st.scrollBy({left:nb.dataset.dir*st.clientWidth*.8,behavior:'smooth'});return}
  const f=e.target.closest('figure[data-g]');if(f)openLb(+f.dataset.g,+f.dataset.i);
});
let LB=[0,0];
function openLb(g,i){const it=DESIGN[g].items;i=(i+it.length)%it.length;LB=[g,i];$('#lb img').src=it[i][0];$('#lb .cap').textContent=it[i][1]+'  ·  '+(i+1)+' / '+it.length;$('#lb').classList.add('on')}
$('#lb').onclick=e=>{if(e.target.closest('.pv'))return openLb(LB[0],LB[1]-1);if(e.target.closest('.nx'))return openLb(LB[0],LB[1]+1);if(e.target.tagName!=='IMG')$('#lb').classList.remove('on')};
document.addEventListener('keydown',e=>{if(!$('#lb').classList.contains('on'))return;if(e.key==='Escape')$('#lb').classList.remove('on');if(e.key==='ArrowLeft')openLb(LB[0],LB[1]-1);if(e.key==='ArrowRight')openLb(LB[0],LB[1]+1)});

// меню, шапка, появление блоков
$('#burger').onclick=()=>$('#menu').classList.toggle('open');
$('#menu').onclick=e=>{if(e.target.tagName==='A')$('#menu').classList.remove('open')};
addEventListener('scroll',()=>{$('header').classList.toggle('scrolled',scrollY>10);$('#totop').classList.toggle('on',scrollY>500)},{passive:true});
document.querySelectorAll('#totop,.foot-top').forEach(b=>b.onclick=e=>{e.preventDefault();scrollTo({top:0,behavior:'smooth'})});
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
